vim.opt.runtimepath:prepend(vim.fn.getcwd())
local walker = require("walker")
local doc = require("walker.document")
local passed, failed = 0, 0
local notices, select_callback, input_callback
vim.notify = function(message) notices[#notices + 1] = message end
vim.ui.select = function(_, _, callback) select_callback = callback end
vim.ui.input = function(_, callback) input_callback = callback end

local function eq(actual, expected)
  assert(vim.deep_equal(actual, expected), "Expected " .. vim.inspect(expected) .. ", got " .. vim.inspect(actual))
end

local function lines(buf)
  return vim.api.nvim_buf_get_lines(buf or 0, 0, -1, false)
end

local function parsed(buf)
  buf = buf or vim.api.nvim_get_current_buf()
  return assert(doc.parse(lines(buf), vim.bo[buf].commentstring))[1]
end

local function setup(text, cs)
  notices, select_callback, input_callback = {}, nil, nil
  walker.setup({ enabled = false })
  vim.cmd("enew!")
  vim.bo.commentstring = cs or ""
  vim.api.nvim_buf_set_lines(0, 0, -1, false, text or { "first", "second", "third" })
  walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", "complete" }, confirm_build = false })
  return vim.api.nvim_get_current_buf()
end

local function test(name, fn)
  local ok, err = pcall(fn)
  if ok then passed = passed + 1; print("PASS " .. name)
  else failed = failed + 1; print("FAIL " .. name .. ": " .. tostring(err)) end
end

test("bare selected WalkerTask prompts and creates a runnable task", function()
  setup()
  vim.cmd("2WalkerTask")
  assert(select_callback, "Expected a mode picker instead of E471")
  select_callback("plan")
  assert(input_callback, "Expected an instruction prompt")
  input_callback("Improve the passage")
  local task = parsed()
  eq(task.mode, "plan")
  eq(task.instructions, { "Improve the passage" })
  eq(doc.snapshot(task, lines(), "").target, { "second" })
  vim.cmd("WalkerRun " .. task.id)
  assert(vim.wait(3000, function() return not walker.status().active end, 5))
  eq(parsed().mode, "planned")
end)

test("mode-only command prompts for instruction", function()
  setup()
  vim.cmd("1,2WalkerTask review")
  assert(input_callback)
  input_callback("Check flow")
  eq(parsed().mode, "review")
end)

test("cancelled prompts do not modify the buffer", function()
  setup()
  local before = lines()
  vim.cmd("1WalkerTask")
  assert(select_callback)
  select_callback(nil)
  eq(lines(), before)
  vim.cmd("1WalkerTask plan")
  assert(input_callback)
  input_callback(nil)
  eq(lines(), before)
end)

test("prompt callback uses original buffer even when focus changes", function()
  local original = setup()
  vim.cmd("2WalkerTask plan")
  assert(input_callback)
  local other = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(other)
  vim.bo.filetype = "snacks_input"
  input_callback("Keep the original selection")
  eq(lines(other), { "" })
  local task = parsed(original)
  eq(doc.snapshot(task, lines(original), "").target, { "second" })
end)

test("editing while a prompt is open cancels stale selection", function()
  setup()
  vim.cmd("2WalkerTask plan")
  assert(input_callback)
  vim.api.nvim_buf_set_lines(0, 0, 0, false, { "inserted" })
  local before = lines()
  input_callback("Do not overwrite")
  eq(lines(), before)
  assert(notices[#notices]:match("changed"))
end)

test("WalkerCancel revokes pending task prompts", function()
  setup()
  vim.cmd("2WalkerTask plan")
  assert(input_callback)
  walker.cancel()
  input_callback("Cancelled instruction")
  eq(lines(), { "first", "second", "third" })
end)

test("selected shorthand directive is expanded without becoming target text", function()
  setup({ "@walker #plan #story Improve flow", "The passage.", "Untouched." })
  vim.cmd("1,2WalkerTask")
  local task = parsed()
  eq(task.mode, "plan")
  eq(task.instructions, { "#story Improve flow" })
  eq(doc.snapshot(task, lines(), "").target, { "The passage." })
  eq(lines()[#lines()], "Untouched.")
end)

test("shorthand immediately above the selection is expanded", function()
  for _, cs in ipairs({ "", "-- %s", "<!-- %s -->" }) do
    setup({ doc.wrap("@walker #review", cs), "", "The passage." }, cs)
    vim.cmd("3WalkerTask")
    assert(input_callback)
    input_callback("Check grammar")
    local task = parsed()
    eq(task.mode, "review")
    eq(doc.snapshot(task, lines(), "").target, { "The passage." })
  end
end)

test("bare @walker can be expanded with explicit arguments", function()
  setup({ "@walker", "The passage." })
  vim.cmd("1,2WalkerTask plan Improve flow")
  eq(parsed().mode, "plan")
  eq(doc.snapshot(parsed(), lines(), "").target, { "The passage." })
end)
test("selected natural-language directives default to build and retain the goal", function()
  setup({ "@walker Improve this passage", "The passage.", "Untouched." })
  vim.cmd("1,2WalkerTask")
  local parsed = assert(doc.scan(lines(), vim.bo.commentstring))
  eq(parsed[1].mode, "build")
  eq(parsed[1].instructions, { "Improve this passage" })
  eq(doc.snapshot(parsed[1], lines(), "").target, { "The passage." })
end)

test("malformed and duplicate headers have distinct actionable errors", function()
  local _, malformed = doc.parse({ "@walker #plan" }, "")
  assert(malformed:match("WalkerTask"), malformed)
  assert(not malformed:match("duplicate"), malformed)
  setup()
  vim.cmd("1WalkerTask plan Improve")
  local source = lines()
  vim.list_extend(source, vim.deepcopy(source))
  local _, duplicate = doc.parse(source, "")
  assert(duplicate:match("Duplicate task ID"), duplicate)
end)

test("notification buffers are rejected before parsing or prompting", function()
  setup({ "@walker #plan" })
  vim.bo.filetype = "snacks_notif"
  vim.bo.buftype = "nofile"
  local before = lines()
  vim.cmd("WalkerRun")
  assert(notices[#notices]:match("document buffer"), notices[#notices])
  vim.cmd("1WalkerTask")
  assert(notices[#notices]:match("document buffer"), notices[#notices])
  assert(not select_callback and not input_callback)
  eq(lines(), before)
end)

test("no range remains explicit and read-only buffers stay unchanged", function()
  setup()
  vim.cmd("WalkerTask")
  assert(notices[#notices]:match("Select"))
  assert(not select_callback)
  vim.bo.readonly = true
  vim.cmd("1WalkerTask plan Improve")
  eq(lines(), { "first", "second", "third" })
  vim.bo.readonly = false
end)

test("structured incomplete blocks are not silently repaired", function()
  setup({ "@walker existing #plan", "Do not discard these notes", "passage" })
  local before = lines()
  vim.cmd("3WalkerTask plan Improve")
  eq(lines(), before)
  assert(notices[#notices]:match("Unclosed"))
end)

test("Run, Build and Task continue an existing plan without nesting or expanding scope", function()
  for _, command in ipairs({ "WalkerRun", "WalkerBuild", "%WalkerTask", "%WalkerTask build", "WalkerTask" }) do
    local source = doc.compact("existing", "planned", "Implement this plan", {}, { "make it work" }, "")
    table.insert(source, "Unrelated human prose")
    setup(source)
    vim.cmd(command)
    assert(vim.wait(3000, function() return not walker.status().active end, 5))
    eq(parsed().mode, "built")
    eq(parsed().id, "existing")
    eq(doc.snapshot(parsed(), lines(), "").target, { "MAKE IT WORK" })
    eq(lines()[#lines()], "Unrelated human prose")
    eq(#assert(doc.parse(lines(), "")), 1)
  end
end)

test("continuation retains confirmation and rejects edits made during confirmation", function()
  setup(doc.compact("existing", "planned", "Implement", {}, { "Plan" }, ""))
  walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", "complete" }, confirm_build = true })
  vim.cmd("WalkerBuild")
  assert(select_callback)
  assert(not walker.status().active)
  vim.api.nvim_buf_set_lines(0, 1, 2, false, { "Human revision" })
  local before = lines()
  select_callback("Build")
  assert(not walker.status().active)
  eq(lines(), before)
  assert(notices[#notices]:find("changed during confirmation", 1, true))
end)

test("selecting multiple tasks is rejected rather than widening scope", function()
  local source = doc.compact("a", "planned", "First", {}, { "first plan" }, "")
  vim.list_extend(source, doc.compact("b", "planned", "Second", {}, { "second plan" }, ""))
  setup(source)
  vim.cmd("%WalkerTask")
  eq(lines(), source)
  assert(not walker.status().active)
  assert(notices[#notices]:find("multiple tasks", 1, true))
end)

test("completed-task continuation respects disabled buffers", function()
  setup(doc.compact("existing", "planned", "Implement", {}, { "Plan" }, ""))
  walker.disable()
  local before = lines()
  vim.cmd("WalkerBuild")
  eq(lines(), before)
  assert(not walker.status().active)
end)

walker.setup({ enabled = false })
print(string.format("%d command tests passed; %d failed", passed, failed))
vim.cmd(failed > 0 and "cquit 1" or "qa!")
