vim.opt.runtimepath:prepend(vim.fn.getcwd())
local walker, doc = require("walker"), require("walker.document")
local usage = require("walker.usage")
local passed = 0
vim.notify = function() end
local function eq(a, b) assert(vim.deep_equal(a, b), vim.inspect(a) .. " ~= " .. vim.inspect(b)) end
local function text() return vim.api.nvim_buf_get_lines(0, 0, -1, false) end
local function tasks() return assert(doc.scan(text(), vim.bo.commentstring)) end
local function wait(fn) assert(vim.wait(4000, fn, 5), vim.inspect(walker.status())) end
local function setup(source, trigger, scenario)
  walker.setup({ enabled = false })
  vim.cmd("enew!")
  vim.bo.commentstring = "<!-- %s -->"
  vim.bo.filetype = "markdown"
  vim.api.nvim_buf_set_lines(0, 0, -1, false, source)
  walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", scenario or "complete" },
    triggers = trigger and { [trigger] = true } or {}, confirm_build = false,
    debounce_ms = 15, idle_ms = 30, interval_ms = 40, cooldown_ms = 1 })
end
local function test(name, fn) fn(); passed = passed + 1; print("PASS " .. name) end

local function run()
  test("plain requests carry out the supplied goal without asking it again", function()
    local goal = "can you write this python code to an actual python runnable file in this file's parent directory"
    setup({ "print('hello')", "@walker " .. goal }, "save")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return not walker.status().active end)
    eq(tasks()[1].mode, "built")
    eq(tasks()[1].instructions, { goal })
    assert(not tasks()[1].tags:find("#needs-instruction", 1, true))
    eq(text()[1], "print('hello')")
  end)
  test("standalone build continues the adjacent completed plan", function()
    local source = doc.compact("existing", "planned", "Write Python", {}, { "A short plan", "Human answer: Python" }, "<!-- %s -->")
    vim.list_extend(source, { "", "#build", "Unrelated text" })
    setup(source, "save")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return not walker.status().active end)
    eq(#tasks(), 1)
    eq(tasks()[1].id, "existing")
    eq(tasks()[1].mode, "built")
    eq(doc.snapshot(tasks()[1], text(), "").target, { "A SHORT PLAN", "HUMAN ANSWER: PYTHON" })
    eq(text()[#text()], "Unrelated text")
  end)
  test("bare and @walker build inside or after a result reuse its identity", function()
    for _, command in ipairs({ "#build", "@walker #build", "<!-- #build -->" }) do
      for _, inside in ipairs({ true, false }) do
        local source = doc.compact("same", "reviewed", "Improve prose", { "original" }, { "Fix grammar" }, "<!-- %s -->")
        table.insert(source, inside and #source or #source + 1, command)
        setup(source, "save")
        vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
        wait(function() return not walker.status().active end)
        eq(#tasks(), 1)
        eq(tasks()[1].id, "same")
        eq(tasks()[1].mode, "built")
        eq(doc.snapshot(tasks()[1], text(), "").target, { "ORIGINAL" })
      end
    end
  end)
  test("build continuation ignores fences, target text, and nonadjacent commands", function()
    local source = doc.compact("safe", "planned", "Keep scope", { "#build" }, { "```text", "#build", "```" }, "<!-- %s -->")
    vim.list_extend(source, { "unrelated text", "#build" })
    setup(source, "save")
    local before = text()
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    eq(text(), before)
    assert(not walker.status().active)
    eq(walker.status().tokens, 0)
  end)
  test("continuation selects the adjacent task, not another task or surrounding text", function()
    local source = doc.compact("first", "planned", "First goal", {}, { "first plan" }, "<!-- %s -->")
    vim.list_extend(source, { "outside" })
    vim.list_extend(source, doc.compact("second", "planned", "Second goal", {}, { "second plan" }, "<!-- %s -->"))
    vim.list_extend(source, { "#build", "outside too" })
    setup(source, "save")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return not walker.status().active end)
    eq(tasks()[1].mode, "planned")
    eq(tasks()[2].mode, "built")
    eq(doc.snapshot(tasks()[2], text(), "").target, { "SECOND PLAN" })
    eq(text()[#text()], "outside too")
  end)
  test("new work waits for insert leave instead of capturing half-typed directives", function()
    for _, trigger in ipairs({ "directive", "save" }) do
      setup({ "@walker #plan A complete goal" }, trigger)
      local mode = vim.fn.mode
      vim.fn.mode = function() return "i" end
      vim.api.nvim_buf_set_lines(0, 0, 1, false, { "@walker #plan A complete goal, still typing" })
      if trigger == "save" then vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 }) end
      vim.wait(70, function() return false end)
      local count = #tasks()
      vim.fn.mode = mode
      eq(count, 0)
      vim.api.nvim_exec_autocmds("InsertLeave", { buffer = 0 })
      wait(function() return #tasks() == 1 and tasks()[1].mode == "planned" end)
    end
  end)
  test("a build requested during cooldown is delayed, not lost", function()
    setup({ "@walker #plan Outline" })
    walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", "complete" },
      triggers = { save = true }, confirm_build = false, cooldown_ms = 400 })
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return tasks()[1].mode == "planned" end)
    vim.api.nvim_buf_set_lines(0, -1, -1, false, { "#build" })
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return tasks()[1].mode == "built" end)
    eq(#tasks(), 1)
  end)
  test("legacy empty targets can receive their own plan without touching other text", function()
    for _, target_before in ipairs({ true, false }) do
      local block = { "-- @walker legacy #planned", "-- Implement this", "-- @result", "-- Short plan", "-- @endwalker", "-- #build" }
      local target = { "-- @walker-target legacy", "-- @endwalker-target legacy" }
      local source = vim.deepcopy(target_before and target or block)
      vim.list_extend(source, target_before and block or target)
      setup(source, "save")
      vim.bo.commentstring = "-- %s"
      vim.bo.filetype = "lua"
      vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
      wait(function() return not walker.status().active end)
      eq(tasks()[1].mode, "built")
      eq(doc.snapshot(tasks()[1], text(), "").target, { "SHORT PLAN" })
    end
  end)
  test("all automatic triggers recognize shorthand and write visible results", function()
    for _, trigger in ipairs({ "save", "directive", "idle", "interval" }) do
      setup({ "before", "" }, trigger)
      vim.api.nvim_buf_set_lines(0, 1, 2, false, { "@walker #plan Outline the bee play" })
      if trigger == "save" then vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 }) end
      wait(function() return #tasks() == 1 and tasks()[1].mode == "planned" end)
      local task = tasks()[1]
      eq(text()[task.result_marker + 1], "Agent notes")
      eq(text()[1], "before")
      eq(walker.view(vim.api.nvim_get_current_buf()).tasks[1].phase, "complete")
      local before = text()
      vim.wait(120, function() return false end)
      eq(text(), before)
    end
  end)
  test("original multiline example discovers its mode and goal", function()
    setup({ "@walker let's test what you can do", "", "#plan an outline about bees in Antarctica", "" })
    walker.run()
    wait(function() return not walker.status().active end)
    local task = tasks()[1]
    eq(task.mode, "planned")
    assert(task.instructions[1]:find("bees in Antarctica", 1, true))
    eq(doc.snapshot(task, text(), "").target, {})
  end)
  test("build with no scope asks inline without a model call", function()
    setup({ "@walker #build Improve this", "", "Actual prose" }, "save")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    local task = tasks()[1]
    assert(task.tags:find("#needs-scope", 1, true))
    assert(table.concat(task.result, " "):find("Walker question", 1, true))
    assert(not walker.status().active)
    eq(walker.status().tokens, 0)
    eq(walker.view(vim.api.nvim_get_current_buf()).tasks[1].phase, "needs input")
    local row = #text()
    walker.scope(row, row, task.id)
    eq(doc.snapshot(tasks()[1], text(), "").target, { "Actual prose" })
    walker.run(task.id)
    wait(function() return not walker.status().active end)
    eq(tasks()[1].mode, "built")
    eq(doc.snapshot(tasks()[1], text(), "").target, { "ACTUAL PROSE" })
  end)
  test("missing goal can be answered inline and resumed", function()
    setup({ "@walker" }, "save")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    local task = tasks()[1]
    assert(task.tags:find("#needs-instruction", 1, true))
    vim.api.nvim_buf_set_lines(0, task.last - 1, task.last - 1, false, { "Walker answer: #plan Outline the play" })
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return not walker.status().active end)
    eq(tasks()[1].mode, "planned")
  end)
  test("plain requests retain build confirmation and can receive an explicit scope", function()
    setup({ "Original prose", "@walker Improve this prose" }, "save")
    local select, callback = vim.ui.select
    vim.ui.select = function(_, _, done) callback = done end
    walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", "complete" },
      confirm_build = true, triggers = { save = true } })
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    vim.ui.select = select
    assert(callback)
    eq(walker.status().tokens, 0)
    eq(text()[1], "Original prose")
    callback("Cancel")
    walker.scope(1, 1, tasks()[1].id)
    eq(doc.snapshot(tasks()[1], text(), "").target, { "Original prose" })
  end)
  test("model questions remain inline and human answers resume the task", function()
    setup({ "@walker #plan Outline the play" }, "save", "question")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return not walker.status().active end)
    local task = tasks()[1]
    assert(task.tags:find("#needs-input", 1, true))
    assert(table.concat(task.result, " "):find("Which audience?", 1, true))
    vim.api.nvim_buf_set_lines(0, task.last - 1, task.last - 1, false, { "Children" })
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    wait(function() return not walker.status().active end)
    eq(tasks()[1].mode, "planned")
    assert(not tasks()[1].tags:find("#needs-input", 1, true))
  end)
  test("TODO candidates and fenced examples never authorize work", function()
    setup({ "TODO: tighten the ending", "```text", "@walker #build destroy text", "```" }, "save")
    vim.api.nvim_exec_autocmds("BufWritePost", { buffer = 0 })
    assert(not walker.status().active)
    eq(#tasks(), 0)
    local view = walker.view(vim.api.nvim_get_current_buf())
    eq(#view.tasks, 1)
    assert(view.tasks[1].candidate)
  end)
  test("compact tasks survive reparse; output can't create directives", function()
    local source = doc.compact("x", "review", "Review flow", { "Passage" }, { "Visible finding" }, "<!-- %s -->")
    local task = assert(doc.parse(source, "<!-- %s -->"))[1]
    eq(task.result, { "Visible finding" })
    eq(doc.snapshot(task, source, "").target, { "Passage" })
    assert(not doc.propose(source, task, { result = { "@walker #build evil" }, done = true }, "<!-- %s -->"))
    assert(not doc.propose(source, task, { result = { "  #build  " }, done = true }, "<!-- %s -->"))
    assert(not doc.propose(source, task, { result = { "  @walker #build  " }, done = true }, "<!-- %s -->"))
  end)
  test("usage distinguishes reported detail, budgets, costs, and unknowns", function()
    local account = usage.new()
    local pricing = { model = "test", currency = "USD", input_per_million = 2, cached_input_per_million = 1, output_per_million = 3 }
    assert(usage.add(account, { total_tokens = 150, input_tokens = 100, cached_tokens = 40, output_tokens = 50, reasoning_tokens = 10 }, pricing, "test"))
    eq(account.total_tokens, 150)
    assert(math.abs(account.cost - 0.00031) < 0.000000001)
    assert(table.concat(usage.lines(account, 200), " "):find("Task budget left: 50", 1, true))
    assert(usage.add(account, { total_tokens = 20, estimated = true }, pricing, "test"))
    assert(account.estimated and not account.cost_known)
    assert(not usage.add(account, { total_tokens = -1 }, pricing, "test"))
  end)
  test("panel follows document buffers and never becomes a task source", function()
    setup({ "@walker #plan Outline" })
    local source = vim.api.nvim_get_current_buf()
    vim.cmd("WalkerPanel")
    eq(vim.api.nvim_get_current_buf(), source)
    local panel_buf
    for _, buf in ipairs(vim.api.nvim_list_bufs()) do if vim.bo[buf].filetype == "walker_panel" then panel_buf = buf end end
    assert(panel_buf and not vim.bo[panel_buf].modifiable)
    walker.run()
    wait(function() return not walker.status().active end)
    local panel_text = table.concat(vim.api.nvim_buf_get_lines(panel_buf, 0, -1, false), "\n")
    assert(panel_text:find("[complete]", 1, true))
    assert(panel_text:find("Walker [enabled]", 1, true))
    assert(panel_text:find("1 / 32000 tokens (task)", 1, true))
    assert(panel_text:find("L1 Ready to build", 1, true))
    assert(panel_text:find("Task %d%d:%d%d:%d%d · Edit %d%d:%d%d:%d%d"))
    assert(panel_text:find("Quick Reference", 1, true))
    assert(panel_text:find(":WalkerBuild [id]", 1, true))
    assert(not panel_text:find("Session usage", 1, true))
    assert(not panel_text:find("Reasoning", 1, true))
    local view = walker.view(source)
    local root = vim.fs.root(vim.fn.getcwd(), ".git")
    eq(view.root, vim.fn.fnamemodify(root or vim.fn.getcwd(), ":~") .. (root and " (git)" or ""))
    vim.cmd("enew!")
    panel_text = table.concat(vim.api.nvim_buf_get_lines(panel_buf, 0, -1, false), "\n")
    assert(panel_text:find("No tasks", 1, true))
    assert(not walker.status(panel_buf).enabled)
    vim.cmd("WalkerPanel")
  end)
  test("agent suggestions are candidates, not self-authorized tasks", function()
    setup({ "@walker #plan Outline" }, "interval", "suggestion")
    walker.run()
    wait(function() return not walker.status().active end)
    local view = walker.view(vim.api.nvim_get_current_buf())
    eq(#view.tasks, 2)
    assert(view.tasks[2].candidate)
    vim.wait(150, function() return false end)
    eq(walker.status().tokens, 1)
    eq(#tasks(), 1)
  end)
  test("compact panel tracks renamed files and runs from a task's detail row", function()
    setup(doc.compact("existing", "planned", "Implement", {}, { "Plan" }, "<!-- %s -->"))
    vim.api.nvim_buf_set_name(0, "/tmp/opencode/walker-panel-test.md")
    local source = vim.api.nvim_get_current_buf()
    local view = walker.view(source)
    eq(view.name, "walker-panel-test.md")
    eq(view.root, "/tmp/opencode")
    vim.cmd("WalkerPanel")
    local win, buf
    for _, item in ipairs(vim.api.nvim_list_wins()) do
      local candidate = vim.api.nvim_win_get_buf(item)
      if vim.bo[candidate].filetype == "walker_panel" then win, buf = item, candidate end
    end
    assert(win and buf)
    local rendered = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    eq(rendered[2], "/tmp/opencode")
    eq(rendered[3], "walker-panel-test.md")
    for row, line in ipairs(rendered) do
      if line:find("L1 Ready to build", 1, true) then vim.api.nvim_win_set_cursor(win, { row, 0 }) end
    end
    for _, mapping in ipairs(vim.api.nvim_buf_get_keymap(buf, "n")) do if mapping.lhs == "r" then mapping.callback() end end
    wait(function() return tasks()[1].mode == "built" end)
    eq(doc.snapshot(tasks()[1], text(), "").target, { "PLAN" })
    vim.cmd("WalkerPanel")
  end)
  test("cancellation while awaiting provider usage is labelled incomplete", function()
    setup({ "@walker #plan Outline" }, nil, "unreported")
    walker.run()
    wait(function() return walker.status().message == "Waiting for provider response" end)
    walker.cancel()
    local view = walker.view(vim.api.nvim_get_current_buf())
    assert(table.concat(view.task_usage, " "):find("Unreported charges", 1, true))
    assert(table.concat(view.usage_summary, " "):find("Unreported charges", 1, true))
    eq(view.tasks[1].phase, "cancelled")
  end)
  test("balance is optional, cached, and independent of writing", function()
    setup({ "Text" })
    local transport = require("walker.transport")
    local original, starts = transport.start, 0
    transport.start = function(... ) starts = starts + 1; return original(...) end
    walker.refresh_balance()
    eq(starts, 0)
    walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", "complete" }, balance = { enabled = true } })
    walker.refresh_balance()
    wait(function() return table.concat(walker.view(vim.api.nvim_get_current_buf()).balance, " "):find("USD 4.82", 1, true) end)
    walker.refresh_balance()
    eq(starts, 1)
    eq(text(), { "Text" })
    transport.start = original
    walker.setup({ command = { "python3", vim.fn.getcwd() .. "/tests/fake_agent.py", "balance-error" }, balance = { enabled = true } })
    walker.refresh_balance()
    wait(function() return table.concat(walker.view(vim.api.nvim_get_current_buf()).balance, " "):find("unavailable", 1, true) end)
    assert(not walker.status().active)
  end)
  walker.setup({ enabled = false })
  print(passed .. " document-first workflow tests passed")
end
local ok, err = xpcall(run, debug.traceback)
if not ok then print(err); vim.cmd("cquit 1") else vim.cmd("qa!") end
